/**
 * Backend API Error Codes (matching ErrorCode enum in backend)
 */
export const ERROR_CODES = {
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  PROJECT_NUMBER_ALREADY_EXISTED: "PROJECT_NUMBER_ALREADY_EXISTED",
  EMPLOYEE_VISA_NOT_FOUND: "EMPLOYEE_VISA_NOT_FOUND",
  INVALID_PROJECT_STATUS_FOR_DELETION: "INVALID_PROJECT_STATUS_FOR_DELETION",
  CONCURRENT_UPDATE_CONFLICT: "CONCURRENT_UPDATE_CONFLICT",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  ILLEGAL_STATE: "ILLEGAL_STATE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

export default ERROR_CODES;
